name: s3-storage

services:
  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./external-storage/minio/data:/data
    # environment:
    #   - MINIO_ROOT_USER=minio
    #   - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"

  redis:
    image: redis:8
    ports:
      - 46379:6379
    volumes:
      - ./external-storage/redis/data:/data
