name: juicefs-meta

services:
  redis:
    image: valkey/valkey:8-alpine
    ports:
      - 46379:6379
    env_file:
      - .env
    volumes:
      - ./redis/data:/data
      - ./redis/valkey.override.conf:/etc/valkey/valkey.override.conf
    command: >
      sh -c 'cat /etc/valkey/valkey.override.conf | valkey-server -'
    healthcheck:
      test: redis-cli ping || exit 1