name: juicefs-meta

services:
  redis:
    image: redis:7-alpine
    ports:
      - 46379:6379
    env_file:
      - .env
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf
    command: |
        sh -c ' if [ -z "${PANEL_REDIS_ROOT_PASSWORD}" ]; then
          redis-server /etc/redis/redis.conf
        else
          redis-server /etc/redis/redis.conf --requirepass ${PANEL_REDIS_ROOT_PASSWORD}
        fi'
