name: juicefs-mount

services:
  format_juicefs:
    image: juicedata/mount
    env_file:
      - .env
    command: >
      sh -c "test -e /juicefs_created || \
      (juicefs format --storage ${STORAGE_TYPE} --bucket ${BUCKET} --access-key=${ACCESS_KEY} --secret-key=${SECRET_KEY} ${META_URL} ${VOL_NAME}  && \
      touch /juicefs_created)"

  juicefs_mount:
    image: juicedata/mount
    env_file:
      - .env
    volumes:
      - ./jfslocal:/mnt/jfs:rw,rshared
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    command: >
      juicefs mount --cache-size ${CACHE_SIZE} ${META_URL} /mnt/jfs
    restart: unless-stopped
    labels:
      - com.docker-tc.enabled=${TC_ENABLED:-0}
      - com.docker-tc.limit=${TC_LIMIT:-10mbit}
    depends_on:
      format_juicefs:
        condition: service_completed_successfully

  debian:
    profiles:
      - test
    image: debian:latest
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./jfslocal:/mnt/jfslocal
      # - jfsvol:/mnt/jfs
      # - jfstest:/mnt/jfstest

# volumes:
#   jfsvol:
#   jfstest:
#     driver: juicedata/juicefs
#     driver_opts:
#       name: ${VOL_NAME}
#       metaurl: ${META_URL}
#       storage: ${STORAGE_TYPE}
#       bucket: ${BUCKET}
#       access-key: ${ACCESS_KEY}
#       secret-key: ${SECRET_KEY}
#       cache-size: 10240
